### ISSUE TITLE
Upcoming: Harbour-MVP Community Call 1

### ISSUE THREAD

**Issue by pet3r-pan** [Meta-tx/PM#1]
Date & time: 18th Oct 5:00PM CEST

Agenda: https://hackmd.io/hfdlXet-RLiEJGHV4gylZg?edit

Calendar invite: https://calendar.google.com/event?action=TEMPLATE&tmeid=M2kydmxmbDAzbnFiNXAwcmc1bnZqdnYwNHEgcGV0ZXJkZW5uaXNwYW5AbQ&tmsrc=peterdennispan%40gmail.com

**Comment by davecraige** [comment]
Sweet

**Comment by pet3r-pan** [comment]
great success
